extends SceneTree
## Local M07 states and the unchanged M06 numerical boundary.
var checks := 0
var failures: Array[String] = []
func _initialize() -> void: call_deferred("verify")
func check(ok: bool, title: String) -> void:
	checks+=1
	if not ok: failures.append(title)
	print("PASS ACTIVE COMBAT: " if ok else "FAIL ACTIVE COMBAT: ",title)
func verify() -> void:
	timelines();defense();reactions();definitions()
	print("ACTIVE COMBAT RESULT ",checks-failures.size(),"/",checks)
	quit(0 if failures.is_empty() else 1)
func timelines() -> void:
	var clock := ActionTimeline.new(1,0.5,[{"start":1.0,"duration":0.5}],0.5)
	check(clock.valid and clock.state()==ActionTimeline.State.INTENT,"Intent exists before start")
	check(clock.start() and clock.state()==ActionTimeline.State.STARTUP and clock.phase_index()==-1,"Startup has no contact")
	check(not clock.start(),"Action cannot restart")
	clock.tick(0.5)
	check(clock.state()==ActionTimeline.State.COMMIT and clock.committed() and not clock.cancel(),"Commit prevents free cancellation")
	clock.tick(0.5)
	check(clock.state()==ActionTimeline.State.ACTIVE and clock.phase_index()==0,"Active begins at authored boundary")
	clock.tick(0.5)
	check(clock.state()==ActionTimeline.State.RECOVERY and clock.phase_index()==-1,"Active end is exclusive")
	clock.tick(0.5)
	check(clock.state()==ActionTimeline.State.COMPLETED and not clock.interrupt(),"Completed is terminal")
	var early := ActionTimeline.new(1,0.5,[{"start":1,"duration":1}],1)
	early.start()
	check(early.cancel() and early.state()==ActionTimeline.State.INTERRUPTED,"Explicit pre-commit cancellation")
	var interrupted := ActionProfiles.clock(0,1,1)
	interrupted.start()
	check(interrupted.interrupt() and interrupted.state()==ActionTimeline.State.INTERRUPTED,"Confirmed interrupt ends Active")
	interrupted.tick(10)
	check(interrupted.phase_index()==-1 and not interrupted.start(),"Interrupted action never resumes")
	clock=ActionTimeline.new(0,0,[{"start":0,"duration":0.2},{"start":0.4,"duration":0.2}],0.2)
	clock.start();clock.tick(0.25)
	check(clock.phase_index()==-1 and clock.state()==ActionTimeline.State.COMMIT,"Explicit phase gap has no contact")
	clock.tick(0.2)
	check(clock.phase_index()==1,"New hit phase has its own index")
	clock.finish_active()
	check(clock.state()==ActionTimeline.State.RECOVERY,"Release ends Active and retains Recovery")
	var before := clock.elapsed
	clock.tick(NAN);clock.tick(-1)
	check(clock.elapsed==before,"Invalid time cannot advance or rewind")
	for bad in [ActionTimeline.new(-1,0,[],0),ActionTimeline.new(1,2,[{"start":1,"duration":1}],0),ActionTimeline.new(0,0,[],0),ActionTimeline.new(0,0,[{"start":0,"duration":0}],0),ActionTimeline.new(0,0,[{"start":0,"duration":1},{"start":0.5,"duration":1}],0),ActionTimeline.new(0,0,[{"start":0,"duration":INF}],0),ActionTimeline.new(0,0,[{"start":"zero","duration":1}],0)]:
		check(not bad.valid and not bad.start(),"Malformed action windows rejected")
	var spell := ActionProfiles.spell(Content.section("spells").bolt)
	spell.start();spell.finish_active()
	check(is_equal_approx(spell.remaining(),float(Content.section("spells").bolt.cooldown)),"Spell retains its full existing cooldown as Recovery")
func defense() -> void:
	var d := ActiveDefense.new()
	var cfg: Dictionary=Content.section("active_combat").defense
	var direct := ActionProfiles.rules("direct")
	check(d.outcome(Vector2.RIGHT,direct,false,cfg).kind==&"hit","Normal yields Hit deterministically")
	check(d.block(true,Vector2.RIGHT) and d.blocks_offense(),"Block is an active stance")
	var blocked := d.outcome(Vector2.RIGHT,direct,false,cfg)
	check(blocked.kind==&"block" and blocked.damage_scale==cfg.block_damage_scale and blocked.impact_scale==cfg.block_impact_scale,"Block only supplies M06 scales")
	check(d.outcome(Vector2.LEFT,direct,false,cfg).kind==&"hit","Rear attack bypasses frontal block")
	check(d.outcome(Vector2.RIGHT,ActionProfiles.rules("ground"),false,cfg).kind==&"hit","Non-blockable area remains Hit")
	check(d.parry(float(cfg.parry_window),float(cfg.parry_recovery),Vector2.RIGHT) and d.mode==ActiveDefense.Mode.PARRY,"Parry replaces Block")
	check(not d.block(true,Vector2.RIGHT) and not d.dodge(0.2,0.2) and not d.parry(0.1,0.1,Vector2.RIGHT),"Conflicting inputs cannot stack or refresh defense")
	check(d.outcome(Vector2.RIGHT,direct,false,cfg).kind==&"parry","Correct timing yields exactly Parry")
	check(d.outcome(Vector2.RIGHT,ActionProfiles.rules("area"),false,cfg).kind==&"hit","Ineligible Parry grants no fallback Block")
	d.tick(float(cfg.parry_window)+0.01)
	check(d.mode==ActiveDefense.Mode.RECOVERY and d.outcome(Vector2.RIGHT,direct,false,cfg).kind==&"hit" and d.blocks_offense(),"Failed Parry exposes actor during Recovery")
	d.tick(1)
	check(d.mode==ActiveDefense.Mode.NORMAL and not d.blocks_offense(),"Parry Recovery restores controls")
	d.parry(float(cfg.parry_window),float(cfg.parry_recovery),Vector2.RIGHT);d.parry_confirmed()
	check(d.mode==ActiveDefense.Mode.RECOVERY and d.outcome(Vector2.RIGHT,direct,false,cfg).kind==&"hit","Successful Parry is consumed without auto-counter")
	d.reset();d.dodge(0.2,0.3)
	check(d.outcome(Vector2.LEFT,direct,false,cfg).kind==&"evade","Dodge yields Evade")
	d.tick(0.21)
	check(d.mode==ActiveDefense.Mode.RECOVERY and d.outcome(Vector2.LEFT,direct,false,cfg).kind==&"hit" and not d.blocks_offense(),"Dodge protection ends before reactivation recovery")
	d.tick(1);d.block(true,Vector2.RIGHT)
	check(d.outcome(Vector2.RIGHT,direct,true,cfg).kind==&"evade","Existing protection wins without stacking")
	d.block(false,Vector2.RIGHT)
	check(d.mode==ActiveDefense.Mode.NORMAL,"Release ends Block")
func reactions() -> void:
	var cfg: Dictionary=Content.section("active_combat").reaction
	var reaction := CombatReaction.new()
	var resolved := HitResolver.resolve(AttackProfile.new(1,&"test",80),CombatStats.new(),DefenseOutcome.hit())
	check(reaction.apply(resolved,Vector2.RIGHT,cfg)==CombatReaction.Kind.NORMAL and reaction.displacement==Vector2(80,0),"Existing normal impact retains displacement")
	resolved=HitResolver.resolve(AttackProfile.new(1,&"test",130),CombatStats.new(),DefenseOutcome.hit())
	check(reaction.apply(resolved,Vector2.RIGHT,cfg)==CombatReaction.Kind.STAGGER and reaction.locked(),"M06 effective impact drives Stagger")
	var time := reaction.remaining
	for i in 10: reaction.apply(resolved,Vector2.RIGHT,cfg)
	check(reaction.remaining==time,"Repeated impact cannot prolong Stagger")
	reaction.tick(time+0.01)
	check(not reaction.locked() and reaction.guard_remaining>0 and reaction.apply(resolved,Vector2.RIGHT,cfg)==CombatReaction.Kind.NORMAL,"Recovery guard prevents immediate stagger loop")
	reaction.tick(2)
	resolved=HitResolver.resolve(AttackProfile.new(1,&"test",130),CombatStats.new(0,{},100),DefenseOutcome.hit())
	check(resolved.impact==65 and reaction.apply(resolved,Vector2.RIGHT,cfg)==CombatReaction.Kind.NORMAL,"Stability is applied once by M06")
	resolved=HitResolver.resolve(AttackProfile.new(1,&"test",100),CombatStats.new(),DefenseOutcome.hit())
	check(reaction.apply(resolved,Vector2.RIGHT,cfg)==CombatReaction.Kind.INTERRUPT,"Intermediate impact produces Interrupt")
	reaction.tick(2);reaction.counter(0.45,0.65)
	check(reaction.locked() and reaction.remaining==0.45 and reaction.guard_remaining>reaction.remaining,"Counter opportunity is bounded")
	reaction.counter(0.45,0.65)
	check(reaction.remaining==0.45,"Counter cannot refresh its guard")
	reaction.tick(2)
	resolved=HitResolver.resolve(AttackProfile.new(0,&"test",1000),CombatStats.new(),DefenseOutcome.hit())
	reaction.apply(resolved,Vector2(2,0),cfg)
	check(reaction.displacement.length()==cfg.max_displacement,"Displacement is bounded")
func definitions() -> void:
	check(ActionProfiles.pulses(2.8,0.9).windows.size()==4,"Existing thorn duration defines four phases")
	check(not ActionProfiles.pulses(2.8,0).valid and not ActionProfiles.pulses(2.8,0.00001).valid,"Zero intervals and runaway phase counts rejected")
	var original := Content.all().duplicate(true)
	check(ContentValidator.validate_bundle(original,Content.vault(),Content.discoveries()).is_empty(),"Shipped M07 content passes validation")
	for sample in [["defense","block_damage_scale",1.1],["defense","block_impact_scale",-0.1],["defense","block_movement_scale",true],["defense","parry_window",0],["defense","parry_window",INF],["defense","counter_window","slow"],["defense","facing_dot",2],["reaction","interrupt_impact",NAN],["reaction","stagger_impact",1],["reaction","max_displacement",-1],["reaction","recovery_guard",0]]:
		var data := original.duplicate(true)
		data.active_combat[sample[0]][sample[1]]=sample[2]
		var errors := ContentValidator.validate_bundle(data,Content.vault(),Content.discoveries())
		check(not errors.is_empty() and sample[1] in "\n".join(errors),"Invalid field reports actual path: "+str(sample[1]))
	for bad in [0,"yes",null]:
		var data := original.duplicate(true)
		data.active_combat.contacts.direct.parryable=bad
		check(not ContentValidator.validate_bundle(data,Content.vault(),Content.discoveries()).is_empty(),"Eligibility requires a boolean")
	var missing := original.duplicate(true)
	missing.active_combat.defense.erase("parry_window")
	check("active_combat.defense.parry_window" in "\n".join(ContentValidator.validate_bundle(missing,Content.vault(),Content.discoveries())),"Missing window has no hardcoded fallback")
