extends SceneTree
var checks := 0
var failures: Array[String] = []
func _initialize() -> void: call_deferred("verify")
func check(ok: bool, title: String) -> void:
	checks += 1
	if not ok: failures.append(title)
	print("PASS WEAPON CONTRACT: " if ok else "FAIL WEAPON CONTRACT: ",title)
func bad(change: Callable, field: String) -> void:
	var data := Content.weapons().duplicate(true)
	change.call(data)
	var errors := WeaponValidator.validate(data)
	check(not errors.is_empty() and "data/weapons.json" in "\n".join(errors) and field in "\n".join(errors),"Malformed content rejected at "+field)
func verify() -> void:
	check(Content.ensure_loaded() and WeaponValidator.validate(Content.weapons()).is_empty(),"Actual weapon definitions pass release-safe validator")
	check(Content.weapons().is_read_only() and Content.weapons().actions.sword_primary.phases.is_read_only(),"Same recursively immutable content contract")
	bad(func(d): d.actions.sword_primary.erase("commit"),"commit")
	bad(func(d): d.actions.sword_primary.startup=true,"startup")
	bad(func(d): d.actions.sword_primary.hit.damage=NAN,"hit.damage")
	bad(func(d): d.actions.sword_primary.hit.impact=INF,"hit.impact")
	bad(func(d): d.actions.sword_primary.hit.damage=-1,"hit.damage")
	bad(func(d): d.actions.sword_primary.geometry.shape="sphere_3d","shape")
	bad(func(d): d.weapons.sword.portfolio.primary="missing","portfolio.primary")
	bad(func(d): d.weapons.sword.family="unknown","family")
	bad(func(d): d.weapons["Bad ID"]=d.weapons.sword,"Bad ID")
	bad(func(d): d.weapons.warhammer.dual_compatible=true,"dual_compatible")
	bad(func(d): d.actions.sword_primary.commit=9,"commit")
	bad(func(d): d.actions.sword_primary.phases[0].start=0,"phases[0].start")
	bad(func(d): d.actions.sword_primary.follow_ups=["missing"],"follow_ups")
	bad(func(d): d.actions.sword_primary.movement.force=123,"force")
	bad(func(d): d.defenses.sword.block_damage_scale=2,"block_damage_scale")
	bad(func(d): d.actions.spear_primary.geometry.minimum_reach=999,"minimum_reach")
	bad(func(d): d.pairings.test={"main":"sword","off":"bow","combined":"sword_primary"},"pairings.test.off")
	for value in [null,[],true,"wrong"]: check(not WeaponValidator.validate(value).is_empty(),"Invalid document root rejected")
	var clock := ActionTimeline.new(.5,.2,[{"start":.5,"duration":.1}],.3)
	clock.hold_before_active=true
	clock.start();clock.tick(.25)
	check(clock.committed() and not clock.cancel() and not clock.release_hold(),"Draw commitment holds; early release cannot create contact")
	clock.tick(9)
	check(clock.awaiting_release() and clock.phase_index()==-1 and is_equal_approx(clock.elapsed,.5),"Aim holds at startup without contact or second clock")
	check(clock.release_hold() and clock.phase_index()==0,"Release activates existing M07 window")
	clock.finish_active();clock.tick(.3)
	check(clock.state()==ActionTimeline.State.COMPLETED,"Release retains authored recovery")
	clock=ActionTimeline.new(.5,.2,[{"start":.5,"duration":.1}],.3)
	clock.hold_before_active=true;clock.start();clock.tick(1);clock.interrupt()
	check(not clock.release_hold() and clock.phase_index()==-1,"Interrupted draw never releases")
	InputSetup.install()
	check(InputMap.action_get_events("weapon_primary")[0].physical_keycode==KEY_J,"Shared weapon input is explicit J")
	check(InputMap.action_get_events("bolt")[1].button_index==MOUSE_BUTTON_LEFT and InputMap.action_get_events("nova")[1].button_index==MOUSE_BUTTON_RIGHT,"Existing mouse meanings preserved")
	print("WEAPON CONTRACT RESULT ",checks-failures.size(),"/",checks)
	quit(0 if failures.is_empty() else 1)
